version: '2'
services:
  liferay-application-§§INSTANCE:
    image: bibbox/liferay-application
    container_name: liferay-application-§§INSTANCE
    volumes_from:
      - liferay-data-§§INSTANCE
    links:
      - liferay-db-§§INSTANCE
    ports:
      - §§PORT:8080
    environment:
      - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
    depends_on:
      - liferay-data-§§INSTANCE
      - liferay-db-§§INSTANCE
  liferay-db-§§INSTANCE:
    image: postgres:9.5
    container_name: liferay-db-§§INSTANCE
    environment:
      - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
      - POSTGRES_USER=liferay
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=lportal
    volumes_from: 
      - liferay-data-§§INSTANCE
    depends_on:
      - liferay-data-§§INSTANCE
  liferay-data-§§INSTANCE:
    image: bibbox/liferay-data
    container_name: liferay-data-§§INSTANCE
    volumes:
      - §§FOLDER/config/functions:/etc/init.d/functions
      - §§FOLDER/config/liferay:/opt/config/liferay
      - §§FOLDER/config/portal-ext.properties:/opt/liferay/portal-ext.properties
      - §§FOLDER/config/portal-setup-wizard.properties:/opt/config/portal-setup-wizard.properties
      - §§FOLDER/liferay/data:/opt/liferay/data
      - §§FOLDER/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata