version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:
  §§INSTANCE-liferay-application:
    image: bibbox/liferay-application
    container_name: §§INSTANCE-liferay-application
    volumes_from:
      - §§INSTANCE-liferay-data
    links:
      - §§INSTANCE-liferay-db
    ports:
      - §§PORT:8080
    environment:
      - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
    depends_on:
      - §§INSTANCE-liferay-data
      - §§INSTANCE-liferay-db
  §§INSTANCE-liferay-db:
    image: postgres:9.5
    container_name: §§INSTANCE-liferay-db
    environment:
      - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
      - POSTGRES_USER=liferay
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=lportal
    volumes_from: 
      - §§INSTANCE-liferay-data
    depends_on:
      - §§INSTANCE-liferay-data
  §§INSTANCE-liferay-data:
    image: busybox
    container_name: §§INSTANCE-liferay-data
    volumes:
      - ./liferay/data:/opt/liferay/data
      - ./postgresql/data/pgdata:/var/lib/postgresql/data/pgdata